language: go

before_install:
  - pip install --user codecov

go:
  - tip

script:
  - cd impact
  - go build
  - go test -short ../...

after_success:
  - codecov

notifications:
  email: false

sudo: false
